apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dev-agent-instrumentation
spec:
  exporter:
    endpoint: 'http://otel-agent-collector.opentelemetry:4318'
  java:
    env:
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_EXPORTER_OTLP_LOGS_PROTOCOL
        value: http/protobuf
      - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
        value: 'http://otel-agent-collector.opentelemetry:4318/v1/logs'
      - name: OTEL_TRACES_EXPORTER
        value: none
      - name: OTEL_METRICS_EXPORTER
        value: none
      - name: OTEL_BLRP_MAX_QUEUE_SIZE
        value: '2048'
      - name: OTEL_BLRP_MAX_EXPORT_BATCH_SIZE
        value: '512'
      - name: OTEL_BLRP_SCHEDULE_DELAY
        value: '5000'
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MDC_ATTRIBUTES
        value: '*'
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES
        value: 'true'
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES
        value: 'true'
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  sampler:
    argument: '1.0'
    type: parentbased_traceidratio
  defaults: {}
  propagators:
    - tracecontext
    - baggage