apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: jaeger
  labels:
    grafana_datasource: jaeger
spec:
  allowCrossNamespaceImport: false
  datasource:
    access: proxy
    jsonData:
      httpHeaderName1: Authorization
      queryTimeout: 60s
      timeInterval: 30s
    name: Jaeger
    secureJsonData:
      httpHeaderValue1: Bearer ${JAEGER_TOKEN}
    type: jaeger
    url: 'https://jaeger-route.example.com'
  instanceSelector:
    matchLabels:
      grafana: datasource
  resyncPeriod: 10m0s
