---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger-oauth-proxy-sa
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jaeger: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jaeger-route"}}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jaeger-oauth-access
rules:
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jaeger-oauth-proxy-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jaeger-oauth-access
subjects:
- kind: ServiceAccount
  name: jaeger-oauth-proxy-sa
  namespace: opentelemetry
---