{
 "title": "RDS Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "AWS Region",
    "query": "ap-south-1,ap-southeast-2,us-east-2"
   },
   {
    "name": "database",
    "label": "RDS Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": 300,
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Storage Space (GB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": 300,
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": 300,
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read / Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": 300,
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": 300,
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read/Write Throughput (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read/Write Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Freeable Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": 300,
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Replica Lag (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$database" },
     "metricName": "ReplicaLag",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}