#!/usr/bin/env bash
# shellcheck disable=SC2034,SC2044

DIR="$(pwd)"

# Display usage information
function display_help() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Script to validate the manifests generated by Kustomize

Options:
  -d, --directory DIRECTORY        Base directory containing Kustomize overlays
  -e, --enforce-all-schemas        Enable enforcement of all schemas (disables ignoring missing schemas)
  -h, --help                       Display this help text
  -sl, --schema-location LOCATION  Location containing schemas
EOF
}

# Detect kustomize or fallback to kubectl kustomize
if command -v kustomize &>/dev/null; then
  KUSTOMIZE_CMD=(kustomize build)
elif command -v kubectl &>/dev/null; then
  KUSTOMIZE_CMD=(kubectl kustomize)
else
  echo "Error: neither kustomize nor kubectl is in PATH" >&2
  exit 1
fi

# Default flags
IGNORE_MISSING_SCHEMAS="--ignore-missing-schemas"
SCHEMA_LOCATION="${DIR}/openshift-json-schema"
KUSTOMIZE_DIRS="${DIR}"

# Initialize with CLI arguments
function init() {
  while [[ $# -gt 0 ]]; do
    case $1 in
      -d|--directory)
        shift
        KUSTOMIZE_DIRS="$1"
        shift
        ;;
      -e|--enforce-all-schemas)
        IGNORE_MISSING_SCHEMAS=""
        shift
        ;;
      -sl|--schema-location)
        shift
        SCHEMA_LOCATION="$1"
        shift
        ;;
      -h|--help)
        display_help
        exit 0
        ;;
      *)
        echo "Invalid option: $1" >&2
        display_help
        exit 1
        ;;
    esac
  done
}

# Build and validate a single kustomization directory
function kustomization_build() {
  local build_dir="$1"
  if [[ ! -d "${build_dir}" ]]; then
    echo "Error: ${build_dir} is not a directory." >&2
    exit 1
  fi
  echo "Processing directory: ${build_dir}"
  echo "Running kustomize build on: ${build_dir}"

  # Capture both stdout and stderr
  output=$("${KUSTOMIZE_CMD[@]}" "${build_dir}" 2>&1)
  local status=$?

  if [[ ${status} -ne 0 ]]; then
    echo "[ERROR] in ${build_dir}"
    echo "-- kustomize output start --"
    echo "${output}"
    echo "-- kustomize output end --"
    exit 1
  else
    echo "[OK] ${build_dir}"
  fi
}

# Walk through all kustomization directories
function process_kustomization() {
  echo "Validating kustomizations under: ${KUSTOMIZE_DIRS}"
  while IFS= read -r build; do
    kustomization_build "${build}"
  done < <(find "${KUSTOMIZE_DIRS}" -type f -name "kustomization.yaml" -exec dirname {} \;)
}

# Main
init "${@}"
process_kustomization