# Updated Prometheus Configuration for Thanos Integration
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  evaluationInterval: 30s
  serviceAccountName: prometheus-k8s
  walCompression: true
  serviceMonitorSelector:
    matchLabels:
      prometheus: grafana
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  thanos:
    blockSize: 2h
    image: 'quay.io/thanos/thanos:v0.39.2'
    listenLocal: false
    logLevel: info
    objectStorageConfig:
      key: objstore.yml
      name: prometheus-thanos-s3-secret
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    version: v0.39.2
  podMonitorNamespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - opentelemetry
  externalLabels:
    replica: $(HOSTNAME)
  portName: web
  disableCompaction: false
  podMonitorSelector:
    matchLabels:
      prometheus: grafana
  serviceMonitorNamespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - opentelemetry
  scrapeInterval: 30s
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 250Gi
        storageClassName: gp3-csi
  replicas: 2
  ruleSelector:
    matchLabels:
      prometheus: grafana
  retention: 2h