kind: Secret
apiVersion: v1
metadata:
  name: prometheus-thanos-s3-secret
data:
  object-store.yaml: |
    type: S3
    config:
      bucket: ''
      endpoint: s3.<region>.amazonaws.com
      access_key: ''
      secret_key: ''
      insecure: false
type: Opaque