apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: grafana
  name: otel-collector-sm
spec:
  endpoints:
    - interval: 15s
      port: prometheus
  selector:
    matchLabels:
      operator.opentelemetry.io/collector-service-type: base