apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: opentelemetry
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: observability-stack
    prometheus: grafana
  name: metrics-otel-sm
spec:
  endpoints:
    - interval: 15s
      metricRelabelings:
        - action: replace
          regex: '^[^.]+\.(.+)\.[^.]+$'
          replacement: '${1}'
          sourceLabels:
            - exported_instance
          targetLabel: pod
        - action: replace
          regex: '.*\.([^.]+)$'
          replacement: '${1}'
          sourceLabels:
            - exported_instance
          targetLabel: app
        - action: replace
          regex: '^([^.]+)\..*'
          replacement: '${1}'
          sourceLabels:
            - exported_instance
          targetLabel: namespace
        - action: labeldrop
          regex: exported_instance|exported_job|cluster|container|endpoint|environment|instance|job|jvm_thread_daemon|jvm_thread_state|prometheus|prometheus_replica|service|otel_scope_name|otel_scope_version
      port: prometheus
  selector:
    matchLabels:
      operator.opentelemetry.io/collector-service-type: base