apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: jaeger-ds
  labels:
    app.kubernetes.io/name: grafana
    grafana_datasource: jaeger
spec:
  allowCrossNamespaceImport: false
  datasource:
    access: proxy
    jsonData:
      httpHeaderName1: Authorization
      tracesToLogsV2:
        customQuery: true
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: false
        query: '{${__tags}, trace_id="${__trace.traceId}"} '
        spanEndTimeShift: 5m
        spanStartTimeShift: '-5m'
        tags:
          - key: k8s.container.name
            value: app
          - key: k8s.namespace.name
            value: namespace
          - key: k8s.pod.name
            value: pod
    name: jaeger
    type: jaeger
    uid: jaeger
    url: 'http://jaeger-otel-collector-extension:16686'
  instanceSelector:
    matchLabels:
      grafana: datasource
  resyncPeriod: 10m
---