apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/jaeger
- ../base/oauth-proxy
- ../base/opentelemetry
- ../base/prometheus
-  grafana

patches:
- path: prometheus/patch.yml
  target:
    kind: Prometheus
    name: prometheus