apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/jaeger
- ../base/oauth-proxy
- ../base/prometheus
- grafana
- opentelemetry

labels:
  - pairs:
      app.kubernetes.io/part-of: observability-stack

patches:
- path: opentelemetry/lt-patch.yaml
  target:
    kind: Instrumentation
    name: instrumentation
- path: opentelemetry/qam-patch.yaml
  target:
    kind: Instrumentation
    name: instrumentation
