apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/jaeger
- ../base/loadlbalancer
- ../base/opentelemetry
- ../base/prometheus
- grafana
- opentelemetry

labels:
  - pairs:
      app.kubernetes.io/part-of: observability-stack