kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: red-hat-managed=true
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
  name: jaeger-collector-lb
  labels:
    app.kubernetes.io/component: jaeger-collector
    app.kubernetes.io/instance: jaeger
spec:
  type: LoadBalancer
  ports:
    - name: otlp-grpc
      protocol: TCP
      appProtocol: grpc
      port: 4317
      targetPort: 4317
  selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: opentelemetry.jaeger-otel
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/part-of: opentelemetry