apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jaeger-lb.yml
  - loki-lb.yml
  - prometheus-lb.yml

labels:
  - pairs:
      app.kubernetes.io/name: loadbalancer
      app.kubernetes.io/component: vpc-peering

metadata:
  name: hub-loadbalancer
