kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: red-hat-managed=true
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
  name: loki-distributor-lb
  labels:
    app.kubernetes.io/component: distributor
    app.kubernetes.io/instance: loki
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: http
  selector:
    app.kubernetes.io/component: distributor
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-distributed