apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: opentelemetry
spec:
  enableFeatures:
    - exemplar-storage
    - memory-snapshot-on-shutdown
    - auto-gomemlimit
    - native-histograms
  evaluationInterval: 30s
  serviceAccountName: prometheus-k8s
  walCompression: true
  serviceMonitorSelector:
    matchLabels:
      prometheus: grafana
  resources:
    limits:
      cpu: '2'
      memory: 12Gi
    requests:
      cpu: 100m
      memory: 6Gi
  prometheusExternalLabelName: prometheus
  externalLabels:
    cluster: sydney
    prometheus_replica: $(POD_NAME)
    region: ap-southeast-2
    tenant_id: sydney
  portName: web
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  probeSelector:
    matchLabels:
      prometheus: grafana
  podMonitorSelector:
    matchLabels:
      prometheus: grafana
  scrapeConfigSelector: {}
  remoteWrite:
    - metadataConfig:
        send: true
        sendInterval: 1m
      name: mimir-hub
      queueConfig:
        batchSendDeadline: 30s
        capacity: 100000
        maxBackoff: 60s
        maxRetries: 10
        maxSamplesPerSend: 5000
        maxShards: 100
        minBackoff: 1s
        minShards: 5
      remoteTimeout: 30s
      url: 'http://mimir-gateway:8080/api/v1/push'
  scrapeInterval: 30s
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: gp3-csi
  replicas: 1
  ruleSelector:
    matchLabels:
      prometheus: grafana
  replicaExternalLabelName: prometheus_replica
  retention: 24h
  retentionSize: 45GB
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prometheus-k8s
  namespace: opentelemetry
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s-role
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes/metrics
  - verbs:
      - get
    nonResourceURLs:
      - /metrics
      - /metrics/slis
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - nonroot
  - verbs:
      - get
      - create
      - update
    apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses/api
    resourceNames:
      - k8s
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s-rb
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: opentelemetry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-k8s-role
