apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
  labels:
    app: opentelemetry-instrumentation
spec:
  exporter:
    endpoint: 'http://metrics-otel-collector.opentelemetry:4318'
  sampler:
    type: parentbased_traceidratio
    argument: "0.1"
  propagators: [tracecontext, baggage, b3]
  java:
    image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.16.0'
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
    env:
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://jaeger-otel-collector.opentelemetry:4318/v1/traces
      - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
        value: http/protobuf
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "namespace=${K8S_NAMESPACE}"
      - name: OTEL_LOGS_EXPORTER
        value: none