apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- instrumentation.yml

labels:
  - pairs:
      app.kubernetes.io/name: opentelemetry-instrumentation
      app.kubernetes.io/component: instrumentation

patches:
  - target:
      kind: Instrumentation
      name: instrumentation
    patch: |-
      - op: add
        path: /metadata/namespace
        value: qam
