apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
  labels:
    app.kubernetes.io/instance: instrumentation
    app.kubernetes.io/component: opentelemetry
spec:
  exporter:
    endpoint: 'http://otel-collector.opentelemetry:4317'
  java:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://otel-collector.opentelemetry:4317'
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
      - name: OTEL_LOGS_EXPORTER
        value: none
    image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.18.1'
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
  sampler:
    argument: '0.1'
    type: parentbased_traceidratio