apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - collector.yml
  - instrumentation.yml

metadata:
  name: spoke-opentelemetry

patches:
  - target:
      kind: Instrumentation
      name: instrumentation
    patch: |-
      - op: add
        path: /metadata/namespace
        value: qam