apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-agent-collector-sm
  namespace: opentelemetry
  labels:
    prometheus: grafana
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: prometheus
      scrapeTimeout: 25s
  namespaceSelector:
    matchNames:
      - opentelemetry
  selector:
    matchLabels:
      app.kubernetes.io/instance: opentelemetry.otel-agent