---
apiVersion: v1
kind: Secret
metadata:
  name: hub-prometheus-thanos-s3-secret
  namespace: opentelemetry
type: Opaque
data:
  objstore.yml: |
    type: S3
    config:
      bucket: ''
      endpoint: s3.ap-southeast-2.amazonaws.com
      access_key: ''
      secret_key: ''
      insecure: false
