apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-eks
  namespace: prometheus
spec:
  evaluationInterval: 30s
  externalLabels:
    cluster: EKS
    environment: observability
  podMonitorSelector:
    matchLabels:
      release: prometheus
  portName: web
  remoteWrite:
    - metadataConfig:
        send: true
        sendInterval: 1m
      queueConfig:
        batchSendDeadline: 5s
        capacity: 25000
        maxBackoff: 10s
        maxSamplesPerSend: 5000
        maxShards: 30
        minBackoff: 100ms
        minShards: 4
        retryOnRateLimit: true
      remoteTimeout: 30s
      sendExemplars: true
      url: http://mimir-gateway.mimir-ms:80/api/v1/push
  replicas: 1
  resources:
    limits:
      cpu: 600m
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 1Gi
  retention: 1d
  scrapeInterval: 30s
  securityContext:
    fsGroup: 65534
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  probeSelector:
    matchLabels:
      release: prometheus
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: gp3-csi