---
apiVersion: v1
kind: Service
metadata:
  name: loki-oauth-proxy-svc
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: loki-tls
spec:
  selector:
    app: loki-oauth-proxy
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
    name: public
---