apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: jaeger
spec:
  nodeSets:
    - config:
        indices.memory.index_buffer_size: 30%
        indices.memory.min_index_buffer_size: 96mb
        node.roles:
          - master
          - data
          - ingest
        node.store.allow_mmap: false
      count: 3
      name: jaeger
      podTemplate:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms8g -Xmx8g'
              name: elasticsearch
              resources:
                limits:
                  cpu: '2'
                  memory: 16Gi
                requests:
                  cpu: '1'
                  memory: 16Gi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
            storageClassName: gp3-csi
  updateStrategy:
  version: 8.5.3