---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: metrics
spec:
  evaluationInterval: 30s
  serviceAccountName: prometheus-k8s
  walCompression: true
  serviceMonitorSelector:
    matchLabels:
      prometheus: grafana
  thanos:
    blockSize: 2h
    image: 'quay.io/thanos/thanos:v0.39.2'
    minTime: '-6h'
    objectStorageConfig:
      key: objstore.yml
      name: opentelemetry-metrics-secrets
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 256Mi
    version: v0.39.2
  externalLabels:
    receive_cluster: central_observability
    replica: $(HOSTNAME)
  portName: web
  podMonitorSelector:
    matchLabels:
      prometheus: grafana
  remoteWrite:
    - metadataConfig:
        send: true
        sendInterval: 1m
      queueConfig:
        batchSendDeadline: 30s
        capacity: 10000
        maxSamplesPerSend: 20000
        maxShards: 20
        minShards: 1
      url: 'http://ae74411b4e69a4772987fc2578e3e707-285070e4cf3facc2.elb.ap-southeast-2.amazonaws.com:19291/api/v1/receive'
      writeRelabelConfigs:
        - action: replace
          replacement: default
          targetLabel: tenant_id
  scrapeInterval: 30s
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: gp3-csi
  replicas: 2
  ruleSelector:
    matchLabels:
      prometheus: grafana
---